# Generated by Django 6.0.3 on 2026-03-17 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_standing_ratio', models.FloatField(default=0, verbose_name='站立比例')),
                ('teacher_walking_ratio', models.FloatField(default=0, verbose_name='走动比例')),
                ('teacher_writing_ratio', models.FloatField(default=0, verbose_name='板书比例')),
                ('teacher_facing_students_ratio', models.FloatField(default=0, verbose_name='面向学生比例')),
                ('teacher_posture_timeline', models.JSONField(default=list, verbose_name='姿态时序数据')),
                ('student_hand_raising_count', models.IntegerField(default=0, verbose_name='学生举手次数')),
                ('student_standing_count', models.IntegerField(default=0, verbose_name='学生起立次数')),
                ('student_head_down_count', models.IntegerField(default=0, verbose_name='学生低头次数')),
                ('student_behavior_timeline', models.JSONField(default=list, verbose_name='学生行为时序')),
                ('interaction_count', models.IntegerField(default=0, verbose_name='互动次数')),
                ('teacher_movement_range', models.FloatField(default=0, verbose_name='教师活动范围')),
                ('student_attention_ratio', models.FloatField(default=0, verbose_name='学生注意力比例')),
                ('key_frames', models.JSONField(default=list, verbose_name='关键帧路径列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='分析时间')),
            ],
            options={
                'verbose_name': '视频分析结果',
                'verbose_name_plural': '视频分析结果',
                'db_table': 'video_analysis_result',
            },
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='音频标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('file', models.FileField(upload_to='audio/%Y/%m/%d/', verbose_name='音频文件')),
                ('file_type', models.CharField(choices=[('mp3', 'MP3'), ('wav', 'WAV'), ('m4a', 'M4A'), ('other', '其他')], default='other', max_length=20, verbose_name='文件类型')),
                ('duration', models.IntegerField(default=0, verbose_name='时长(秒)')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小(字节)')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='处理状态')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('processed_time', models.DateTimeField(blank=True, null=True, verbose_name='处理完成时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to=settings.AUTH_USER_MODEL, verbose_name='上传用户')),
            ],
            options={
                'verbose_name': '音频文件',
                'verbose_name_plural': '音频文件',
                'db_table': 'audio_file',
                'ordering': ['-upload_time'],
            },
        ),
        migrations.CreateModel(
            name='AudioAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speech_rate', models.FloatField(default=0, verbose_name='语速(字/分钟)')),
                ('pitch_frequency', models.FloatField(default=0, verbose_name='音高基频(Hz)')),
                ('short_time_energy', models.FloatField(default=0, verbose_name='短时能量')),
                ('mfcc', models.JSONField(default=dict, verbose_name='MFCC特征')),
                ('tone_type', models.CharField(default='中性型', max_length=50, verbose_name='语气类型')),
                ('tone_confidence', models.FloatField(default=0, verbose_name='语气识别置信度')),
                ('transcribed_text', models.TextField(blank=True, verbose_name='转写文本')),
                ('question_types', models.JSONField(default=dict, verbose_name='提问类型统计')),
                ('utterance_length_avg', models.FloatField(default=0, verbose_name='平均话语长度')),
                ('valid_speech_duration', models.IntegerField(default=0, verbose_name='有效语音时长(秒)')),
                ('silence_duration', models.IntegerField(default=0, verbose_name='静音时长(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='分析时间')),
                ('audio_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='analysis.audiofile', verbose_name='音频文件')),
            ],
            options={
                'verbose_name': '语音分析结果',
                'verbose_name_plural': '语音分析结果',
                'db_table': 'audio_analysis_result',
            },
        ),
        migrations.CreateModel(
            name='TeacherStyleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='画像名称')),
                ('style_type', models.CharField(choices=[('active_interactive', '活跃互动型'), ('calm_lecture', '沉稳讲授型'), ('walking_guide', '走动引导型'), ('mixed', '混合型')], default='mixed', max_length=50, verbose_name='风格类型')),
                ('style_tags', models.JSONField(default=list, verbose_name='风格标签列表')),
                ('feature_vector', models.JSONField(default=dict, verbose_name='融合特征向量')),
                ('radar_data', models.JSONField(default=dict, verbose_name='雷达图数据')),
                ('timeline_data', models.JSONField(default=dict, verbose_name='时序图数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('audio_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='analysis.audioanalysisresult', verbose_name='语音分析结果')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_profiles', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
                ('video_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='analysis.videoanalysisresult', verbose_name='视频分析结果')),
            ],
            options={
                'verbose_name': '教师风格画像',
                'verbose_name_plural': '教师风格画像',
                'db_table': 'teacher_style_profile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='视频标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('file', models.FileField(upload_to='video/%Y/%m/%d/', verbose_name='视频文件')),
                ('file_type', models.CharField(choices=[('mp4', 'MP4'), ('avi', 'AVI'), ('mov', 'MOV'), ('other', '其他')], default='other', max_length=20, verbose_name='文件类型')),
                ('duration', models.IntegerField(default=0, verbose_name='时长(秒)')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小(字节)')),
                ('frame_count', models.IntegerField(default=0, verbose_name='总帧数')),
                ('fps', models.FloatField(default=0, verbose_name='帧率')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='处理状态')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('processed_time', models.DateTimeField(blank=True, null=True, verbose_name='处理完成时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_files', to=settings.AUTH_USER_MODEL, verbose_name='上传用户')),
            ],
            options={
                'verbose_name': '视频文件',
                'verbose_name_plural': '视频文件',
                'db_table': 'video_file',
                'ordering': ['-upload_time'],
            },
        ),
        migrations.AddField(
            model_name='videoanalysisresult',
            name='video_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='analysis.videofile', verbose_name='视频文件'),
        ),
    ]
