# Generated by Django 6.0.3 on 2026-03-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherstyleprofile',
            name='profile_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='风格画像图片URL'),
        ),
    ]
