# Generated by Django 6.0.3 on 2026-03-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_teacherstyleprofile_profile_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoanalysisresult',
            name='captured_frames',
            field=models.JSONField(default=list, verbose_name='捕获的代表性帧列表'),
        ),
    ]
